name: Bug Report
description: Help improve Revocare by reporting a bug.
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to the Revocare Bug Report!

        Thank you for contributing to Revocare by reporting this bug. Before you start, make sure to search the existing issues to avoid duplicates.
  
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Briefly describe the bug you encountered. What went wrong?"
      placeholder: "Explain the issue in clear terms..."
    validations:
      required: true
 
  - type: textarea
    id: expectedBehavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen? How should the application behave?"
      placeholder: "Describe the expected behavior..."
  
  - type: textarea
    id: actualOutcome
    attributes:
      label: "Actual Outcome"
      description: "Describe what actually occurred."
      placeholder: "Explain the behavior that you observed..."
    
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: | 
                    Attach Screenshots (if applicable)
                    
                    Tip: You can attach files by clicking this text area and then dragging files in.
      placeholder: "Attach any relevant screenshots..."
    
  - type: textarea
    id: solution
    attributes:
      label: "Possible Solution"
      description: "Do you have any thoughts on how to address the issue?"
      placeholder: "Share your potential solution..."

  - type: textarea
    id: moreInfo
    attributes:
      label: "Additional Information"
      description: "Any extra context or details that might help us understand the problem better."
      placeholder: "Provide any relevant information..."
