name: Bug Report
description: Help improve Revocare by reporting a bug.
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "..."
    validations:
      required: true
 
  - type: textarea
    id: expectedBehavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "..."
  
  - type: textarea
    id: actualOutcome
    attributes:
      label: "Actual Outcome"
      description: "Describe what actually occurred."
      placeholder: "..."
    
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "Add Screenshots"
      placeholder: "..."
    
  - type: textarea
    id: moreInfo
    attributes:
      label: "Additional Information"
      description: "Share any extra information about the problem."
      placeholder: "..."
    
  - type: textarea
    id: solution
    attributes:
      label: "Possible Solution"
      placeholder: "..."
