name: Bug Report
about: Help us improve Revocare by reporting a bug.
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: "A clear and concise description of what the bug is."
      placeholder: "..."
    validations:
      required: true
 
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "..."
  
  - type: textarea
    id: actual
    attributes:
      label: "Actual Outcome"
      description: "Describe what actually occurred."
      placeholder: ...
    
    - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "Add Screenshots"
      placeholder: "..."
    
    - type: textarea
    id: moreInfo
    attributes:
      label: "Additional Information"
      description: "Share any extra information about the problem."
      placeholder: "..."
    
    - type: textarea
    id: solution
    attributes:
      label: "Possible Solution"
      placeholder: "..."
