name: Bug Report
description: Help improve Revocare by reporting a bug.
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        `###Welcome to the Revocare Bug Report!`

        Before you start, make sure to search the existing issues to avoid duplicates. If you're certain this is a new issue, please provide the following details:
          - Briefly describe the bug you encountered.
          - Describe the behavior you expected to see.
          - Explain what actually happened.
          - Attach any relevant screenshots.
          - If you have any suggestions for a possible solution, please share them.
          - Additional context or information that might help us understand the problem.
  
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Briefly describe the bug you encountered. What went wrong?"
      placeholder: "Explain the issue in clear terms..."
    validations:
      required: true
 
  - type: textarea
    id: expectedBehavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen? How should the application behave?"
      placeholder: "Describe the expected behavior..."
  
  - type: textarea
    id: actualOutcome
    attributes:
      label: "Actual Outcome"
      description: "Describe what actually occurred."
      placeholder: "..."
    
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "Add Screenshots of the bug"
      placeholder: "Attach any relevant screenshots..."
    
  - type: textarea
    id: solution
    attributes:
      label: "Possible Solution"
      placeholder: "Share your potential solution..."

  - type: textarea
    id: moreInfo
    attributes:
      label: "Additional Information"
      description: "Any extra context or details that might help us understand the problem better."
      placeholder: "Provide any relevant information..."
