name: Chore Request
description: Suggest a task to improve Revocare.
title: "[Chore]: "
labels: ["chore"]

body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to the Revocare Chore Request!

        Thank you for contributing to Revocare by suggesting this new task. Before you start, please search the existing requests to avoid duplicates.
  
  - type: textarea
    id: description
    attributes:
      label: "Task Description"
      description: "Briefly describe the task you're suggesting."
      placeholder: "Explain the task idea..."
    validations:
      required: true
 
  - type: textarea
    id: expectedBehavior
    attributes:
      label: "Expected Behavior"
      description: "What should be the outcome of completing this task?"
      placeholder: "Describe the expected outcome..."
  
  - type: textarea
    id: benefits
    attributes:
      label: "Benefits"
      description: "Share the advantages this task would offer to the platform and its users. How does it enhance the overall experience?"
      placeholder: "Describe the benefits of completing this task..."
    
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: | 
                    Attach Screenshots (if applicable)
                    
                    Tip: You can attach files by clicking this text area and then dragging files in.
      placeholder: "Attach any relevant screenshots..."

  - type: textarea
    id: moreInfo
    attributes:
      label: "Additional Information"
      description: "Any extra context or details that might help us understand the feature better."
      placeholder: "Provide any relevant additional information..."
